
import { TarotCard } from './types';

export const ALL_CARDS: TarotCard[] = [
    // 0-23 Major Arcana
    { name: "Шут", keyword: "Доверие, Начало", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/00_fool.png" },
    { name: "Маг", keyword: "Воля, Мастерство", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/01_magician.png" },
    { name: "Верховная Жрица", keyword: "Тайна, Интуиция", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/02_high_priestess.png" },
    { name: "Императрица", keyword: "Изобилие, Творчество", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/03_empress.png" },
    { name: "Император", keyword: "Структура, Власть", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/04_emperor.png" },
    { name: "Иерофант", keyword: "Традиция, Обучение", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/05_hierophant.png" },
    { name: "Влюбленные", keyword: "Союз, Выбор", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/06_lovers.png" },
    { name: "Колесница", keyword: "Контроль, Победа", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/07_chariot.png" },
    { name: "Справедливость", keyword: "Равновесие, Закон", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/08_justice.png" },
    { name: "Отшельник", keyword: "Поиск, Мудрость", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/09_hermit.png" },
    { name: "Колесо Фортуны", keyword: "Перемены, Судьба", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/10_wheel_of_fortune.png" },
    { name: "Сила", keyword: "Мужество, Стойкость", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/11_strength.png" },
    { name: "Повешенный", keyword: "Жертва, Пауза", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/12_hanged_man.png" },
    { name: "Смерть", keyword: "Трансформация, Конец", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/13_death.png" },
    { name: "Умеренность", keyword: "Синтез, Гармония", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/14_temperance.png" },
    { name: "Дьявол", keyword: "Зависимость, Искушение", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/15_devil.png" },
    { name: "Башня", keyword: "Прозрение, Разрушение", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/16_tower.png" },
    { name: "Звезда", keyword: "Надежда, Вдохновение", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/17_star.png" },
    { name: "Луна", keyword: "Интуиция, Иллюзии", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/18_moon.png" },
    { name: "Солнце", keyword: "Ясность, Радость", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/19_sun.png" },
    { name: "Суд", keyword: "Пробуждение, Искупление", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/20_judgement.png" },
    { name: "Мир", keyword: "Завершение, Целостность", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/21_world.png" },
    { name: "Герой", keyword: "Опыт, Осмысление", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/22_hero.png" },
    { name: "Белая карта", keyword: "Свобода Воли, Потенциал", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/23_white_card.png" },

    // Wands
    { name: "Туз Жезлов", keyword: "Искра", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_01_ace.png" },
    { name: "Двойка Жезлов", keyword: "План", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_02_two.png" },
    { name: "Тройка Жезлов", keyword: "Ожидание", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_03_three.png" },
    { name: "Четверка Жезлов", keyword: "Праздник", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_04_four.png" },
    { name: "Пятерка Жезлов", keyword: "Конкуренция", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_05_five.png" },
    { name: "Шестерка Жезлов", keyword: "Победа", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_06_six.png" },
    { name: "Семерка Жезлов", keyword: "Отстаивание", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_07_seven.png" },
    { name: "Восьмерка Жезлов", keyword: "Скорость", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_08_eight.png" },
    { name: "Девятка Жезлов", keyword: "Стойкость", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_09_nine.png" },
    { name: "Десятка Жезлов", keyword: "Ноша", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_10_ten.png" },
    { name: "Паж Жезлов", keyword: "Энтузиазм", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_11_page.png" },
    { name: "Рыцарь Жезлов", keyword: "Порыв", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_12_knight.png" },
    { name: "Королева Жезлов", keyword: "Харизма", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_13_queen.png" },
    { name: "Король Жезлов", keyword: "Лидерство", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/wands_14_king.png" },

    // Cups
    { name: "Туз Кубков", keyword: "Чувства", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_01_ace.png" },
    { name: "Двойка Кубков", keyword: "Партнерство", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_02_two.png" },
    { name: "Тройка Кубков", keyword: "Празднование", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_03_three.png" },
    { name: "Четверка Кубков", keyword: "Апатия", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_04_four.png" },
    { name: "Пятерка Кубков", keyword: "Потеря", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_05_five.png" },
    { name: "Шестерка Кубков", keyword: "Ностальгия", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_06_six.png" },
    { name: "Семерка Кубков", keyword: "Иллюзии", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_07_seven.png" },
    { name: "Восьмерка Кубков", keyword: "Уход", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_08_eight.png" },
    { name: "Девятка Кубков", keyword: "Наслаждение", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_09_nine.png" },
    { name: "Десятка Кубков", keyword: "Счастье", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_10_ten.png" },
    { name: "Паж Кубков", keyword: "Влюбленность", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_11_page.png" },
    { name: "Рыцарь Кубков", keyword: "Романтика", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_12_knight.png" },
    { name: "Королева Кубков", keyword: "Эмпатия", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_13_queen.png" },
    { name: "Король Кубков", keyword: "Поддержка", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/cups_14_king.png" },

    // Swords
    { name: "Туз Мечей", keyword: "Ясность", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_01_ace.png" },
    { name: "Двойка Мечей", keyword: "Нерешительность", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_02_two.png" },
    { name: "Тройка Мечей", keyword: "Боль", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_03_three.png" },
    { name: "Четверка Мечей", keyword: "Пауза", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_04_four.png" },
    { name: "Пятерка Мечей", keyword: "Конфликт", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_05_five.png" },
    { name: "Шестерка Мечей", keyword: "Переход", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_06_six.png" },
    { name: "Семерка Мечей", keyword: "Хитрость", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_07_seven.png" },
    { name: "Восьмерка Мечей", keyword: "Ограничения", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_08_eight.png" },
    { name: "Девятка Мечей", keyword: "Тревога", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_09_nine.png" },
    { name: "Десятка Мечей", keyword: "Завершение", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_10_ten.png" },
    { name: "Паж Мечей", keyword: "Любопытство", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_11_page.png" },
    { name: "Рыцарь Мечей", keyword: "Решительность", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_12_knight.png" },
    { name: "Королева Мечей", keyword: "Независимость", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_13_queen.png" },
    { name: "Король Мечей", keyword: "Интеллект", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/swords_14_king.png" },

    // Pentacles
    { name: "Туз Пентаклей", keyword: "Шанс", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_01_ace.png" },
    { name: "Двойка Пентаклей", keyword: "Балансирование", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_02_two.png" },
    { name: "Тройка Пентаклей", keyword: "Мастерство", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_03_three.png" },
    { name: "Четверка Пентаклей", keyword: "Стабильность", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_04_four.png" },
    { name: "Пятерка Пентаклей", keyword: "Кризис", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_05_five.png" },
    { name: "Шестерка Пентаклей", keyword: "Щедрость", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_06_six.png" },
    { name: "Семерка Пентаклей", keyword: "Ожидание", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_07_seven.png" },
    { name: "Восьмерка Пентаклей", keyword: "Трудолюбие", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_08_eight.png" },
    { name: "Девятка Пентаклей", keyword: "Благополучие", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_09_nine.png" },
    { name: "Десятка Пентаклей", keyword: "Наследие", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_10_ten.png" },
    { name: "Паж Пентаклей", keyword: "Обучение", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_11_page.png" },
    { name: "Рыцарь Пентаклей", keyword: "Методичность", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_12_knight.png" },
    { name: "Королева Пентаклей", keyword: "Забота", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_13_queen.png" },
    { name: "Король Пентаклей", keyword: "Статус", imageUrl: "https://cdn.jsdelivr.net/gh/marataitester-blip/tarot/pentacles_14_king.png" }
];
